### ISSUE TITLE
Having trouble to build/run

### ISSUE THREAD

**Issue by ansorg** [duncanj/XPDisplay#2]
I use Eclipse. When I run the program there (or create a jar package to run) it stops with 

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.awt.Container.addImpl(Unknown Source)
	at java.awt.Container.add(Unknown Source)
	at xpdisplay.ui.RawDataPanel.<init>(RawDataPanel.java:16)
	at xpdisplay.ui.XPDisplayFrame.<init>(XPDisplayFrame.java:58)
	at xpdisplay.Main$1.run(Main.java:78)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)`

checking at `RawDataPanel.java:16 ` I see that it tries to add `panel1` which is not initialized. If I fix this it will error again in other places where there are uninitialized properties in classes, lots of them.

What am I missing?

thanks

**Comment by duncanj** [comment]
Hi, this source code only really works in Netbeans and is quite old and unmaintained.  The version of XPDisplay that is distributed from the XPDisplay web page is not the same as this source code.

**Comment by ansorg** [comment]
I tried to follow this one :-)

> Q: Why doesn't XPDisplay show X?
A: If X-Plane can send the data, then theoretically XPDisplay could show it. Please feel free to download the source and try changing it. :-) 

Wanted to do some debugging, since with the downloaded version some features do not seem to work in my environment (X-Plane 11 on same computer), namely Glideslope, Vertical Speed, the Pilot Log
